### ISSUE TITLE
Why multiplying by 4 in the code?

### ISSUE THREAD

**Issue by CSTiger77** [TamashaM/NAPA-VQ#1]
In the code, why multipying self.num_class by 4 for NAVQ? For example: 
(1) self.model = network(args.fg_nc * 4, feature_extractor)
(2) self.navq = NAVQ(
            num_classes=self.num_class * 4,
            feat_dim=self.args.emb_size,
            device=device,
        )
and so on.

**Comment by CSTiger77** [comment]
OK, I know the reason of multiplying 4

**Comment by Redredhorse** [comment]
Hello, have you successfully reached the author's experimental results?Setting to cifar100, task_num=10, my accuracy is only 52%

**Comment by Redredhorse** [comment]
Hello, have you successfully reached the author's experimental results?Setting to cifar100, task_num=10, my accuracy is only 58%

**Comment by CSTiger77** [comment]
Me too.

**Comment by TamashaM** [comment]
@CSTiger77 and @Redredhorse, thank you for your interest! In response to the query about accuracy, your reported 58% accuracy aligns with our overall accuracy at the end of the 10th session (See supplementary materials Table 4.). Similar to PASS and SSRE methods, we use the Average accuracy metric in the main text, which calculates the mean across all the incremental sessions.
For detailed information on accuracies and metric definition, check our supplementary materials [PDF link](https://openaccess.thecvf.com/content/ICCV2023/supplemental/Malepathirana_NAPA-VQ_Neighborhood-Aware_Prototype_ICCV_2023_supplemental.pdf).
